export type Giftitem ={
    id: string;
    name: string;
    imageUrl: string;
    category: string;
    price: number;
    isAvailable: boolean;
}

export const gifts: Giftitem[] = [
    // Cozinha
    {
        id: "1",
        name: "Jogo de Panelas",
        imageUrl: "/gifts/jogo_panelas.webp",
        category: "Cozinha",
        price: 565,
        isAvailable: true,
    },
    {
        id: "2",
        name: "Faqueiro",
        imageUrl: "/gifts/faqueiro.webp",
        category: "Cozinha",
        price: 280,
        isAvailable: true,
    },
    {
        id: "3",
        name: "Conjunto de Taças",
        imageUrl: "/gifts/taças.webp",
        category: "Cozinha",
        price: 199,
        isAvailable: true,
    },
    {
        id: "4",
        name: "Multiprocessador",
        imageUrl: "/gifts/liquidificador.webp",
        category: "Cozinha",
        price: 230,
        isAvailable: true,
    },
    {
        id: "5",
        name: "Conjunto de Copos",
        imageUrl: "/gifts/copos.webp",
        category: "Cozinha",
        price: 149,
        isAvailable: true,
    },
    {
        id: "6",
        name: "Airfryer ",
        imageUrl: "/gifts/Airfryer.webp",
        category: "Cozinha",
        price: 500,
        isAvailable: true,
    },
    {
        id: "7",
        name: "Jogo de Banho",
        imageUrl: "/gifts/banho.webp",
        category: "Quarto",
        price: 680,
        isAvailable: true,
    },
    {
        id: "8",
        name: "Jogo de Porcelana",
        imageUrl: "/gifts/xícaras.webp",
        category: "Cozinha",
        price: 339,
        isAvailable: true,
    },
    {
        id: "9",
        name: "Utensílios de Cozinha",
        imageUrl: "/gifts/utensilios.webp",
        category: "Cozinha",
        price: 179,
        isAvailable: true,
    },
    {
        id: "10",
        name: "Cortina para Janela",
        imageUrl: "/gifts/cortina-janela.webp",
        category: "Quarto",
        price: 259,
        isAvailable: true,
    },
    {
        id: "11",
        name: "Conjunto de Taças para sobremesa",
        imageUrl: "/gifts/sobremesa.webp",
        category: "Cozinha",
        price: 165,
        isAvailable: true,
    },
    {
        id: "12",
        name: "Ferro de Passar",
        imageUrl: "/gifts/ferro.webp",
        category: "Lavanderia",
        price: 155,
        isAvailable: true,
    },
    {
        id: "13",
        name: "Formas e Assadeiras",
        imageUrl: "/gifts/formas e assadeiras.webp",
        category: "Cozinha",
        price: 229,
        isAvailable: true,
    },
    {
        id: "14",
        name: "Ventilador",
        imageUrl: "/gifts/ventilador.webp",
        category: "Quarto",
        price: 250,
        isAvailable: true,
    },
    {
        id: "15",
        name: "Jarras",
        imageUrl: "/gifts/jarras.webp",
        category: "Cozinha",
        price: 125,
        isAvailable: true,
    },
    {
        id: "16",
        name: "Almofadas",
        imageUrl: "/gifts/almofadas.webp",
        category: "Sala",
        price: 119,
        isAvailable: true,
    },
    {
        id: "17",
        name: "Travessas e Tigelas",
        imageUrl: "/gifts/travessas.webp",
        category: "Cozinha",
        price: 299,
        isAvailable: true,
    },
    {
        id: "18",
        name: "Mesa de Jantar",
        imageUrl: "/gifts/mesa.webp",
        category: "Sala",
        price: 2000,
        isAvailable: true,
    },
    {
        id: "19",
        name: "Sofá",
        imageUrl: "/gifts/sofa.webp",
        category: "Sala",
        price: 3500,
        isAvailable: true,
    },
    {
        id: "19",
        name: "Ar-condicionado",
        imageUrl: "/gifts/ar.webp",
        category: "Quarto",
        price: 1700,
        isAvailable: true,
    },
    {
        id: "20",
        name: "Travesseiros",
        imageUrl: "/gifts/travesseiros.webp",
        category: "Quarto",
        price: 160,
        isAvailable: true,
    },
    {
        id: "21",
        name: "Roupa de Cama",
        imageUrl: "/gifts/roupa de cama.webp",
        category: "Quarto",
        price: 600,
        isAvailable: true,
    },
    {
        id: "22",
        name: "Microondas",
        imageUrl: "/gifts/microondas.webp",
        category: "Cozinha",
        price: 750,
        isAvailable: true,
    },
    {
        id: "23",
        name: "Máquina de Lavar",
        imageUrl: "/gifts/maquina-de-lavar.webp",
        category: "Lavanderia",
        price: 3500,
        isAvailable: true,
    },
    {
        id: "24",
        name: "Tapete de Sala de Estar",
        imageUrl: "/gifts/tapete.webp",
        category: "Sala",
        price: 500,
        isAvailable: true,
    },
    {
        id: "25",
        name: "Conjunto de Edredom",
        imageUrl: "/gifts/edredom.webp",
        category: "Quarto",
        price: 700,
        isAvailable: true,
    },
    {
        id: "26",
        name: "Tábua de Passar",
        imageUrl: "/gifts/tabuadepassar.webp",
        category: "Lavanderia",
        price: 175,
        isAvailable: true,
    },
    {
        id: "27",
        name: "Chaleira",
        imageUrl: "/gifts/chaleira.webp",
        category: "Cozinha",
        price: 125,
        isAvailable: true,
    },
    {
        id: "28",
        name: "Compra de Mercado",
        imageUrl: "/gifts/compra-mercado.jpg",
        category: "Cozinha",
        price: 1500,
        isAvailable: true,
    },
    {
        id: "29",
        name: "Geladeira",
        imageUrl: "/gifts/geladeira.webp",
        category: "Cozinha",
        price: 2300,
        isAvailable: true,
    },
    {
        id: "30",
        name: "Cafeteira",
        imageUrl: "/gifts/cafeteira.webp",
        category: "Cozinha",
        price: 450,
        isAvailable: true,
    },
    {
        id: "31",
        name: "Cooktop",
        imageUrl: "/gifts/cooktop.webp",
        category: "Cozinha",
        price: 590,
        isAvailable: true,
    },
    {
        id: "32",
        name: "Aspirador de Pó",
        imageUrl: "/gifts/aspirador.webp",
        category: "Lavanderia",
        price: 399,
        isAvailable: true,
    },
    {
        id: "33",
        name: "Guarda-roupa",
        imageUrl: "/gifts/guarda-roupa.webp",
        category: "Quarto",
        price: 1750,
        isAvailable: true,
    },
    {
        id: "34",
        name: "Cama",
        imageUrl: "/gifts/cama.webp",
        category: "Quarto",
        price: 930,
        isAvailable: true,
    },
    {
        id: "35",
        name: "Torradeira",
        imageUrl: "/gifts/torradeira.webp",
        category: "Cozinha",
        price: 149,
        isAvailable: true,
    },
    {
        id: "36",
        name: "Conjunto de Pratos",
        imageUrl: "/gifts/pratos.webp",
        category: "Cozinha",
        price: 400,
        isAvailable: true,
    },
    {
        id: "37",
        name: "Panela de Arroz Elétrica",
        imageUrl: "/gifts/panela-arroz.jpg",
        category: "Cozinha",
        price: 199,
        isAvailable: true,
    },
    {
        id: "38",
        name: "Varal Dobrável",
        imageUrl: "/gifts/varal.webp",
        category: "Lavanderia",
        price: 220,
        isAvailable: true,
    },
];